pub mod divide_before_multiply;

use super::engine::Outcome;
use crate::engine::EngineError;
use crate::report::{Classification, OutcomeReport, ReportSectionFragment};
use crate::utils;
use solang_parser::pt::{Loc, SourceUnit};
use std::collections::HashMap;
use std::path::PathBuf;

pub trait VulnerabilityPattern {
    fn find(source: &mut HashMap<PathBuf, SourceUnit>)
        -> Result<VulnerabilityOutcome, EngineError>;
}

#[macro_export]
macro_rules! vulnerability {
    ($(($name:ident, $report_title:expr, $description:expr, $severity:expr)),+ $(,)?) => {


        $(pub struct $name;)+

        #[allow(non_snake_case)]
        #[derive(Debug)]
        pub enum VulnerabilityTarget {
            $($name,)+
        }


        impl VulnerabilityTarget{
            pub fn find(
                &self,
                source: &mut HashMap<PathBuf, SourceUnit>,
            ) -> Result<VulnerabilityOutcome, EngineError> {
                match self {
                    $(
                        VulnerabilityOutcome::$name => $name::find(source),
                    )+
                }

            }

        }


        #[derive(Debug)]
        pub enum VulnerabilityOutcome {
            $($name(Outcome),)+
        }


        impl VulnerabilityOutcome {
            pub fn len(&self) -> usize {
                match self {
                    $(
                        VulnerabilityOutcome::$name(outcome) => outcome.iter().map(|(_, v)| v.len()).sum(),
                    )+
                }
            }

            pub fn is_empty(&self) -> bool {
                self.len() == 0
            }

            pub fn classification(&self) -> Classification {
                todo!()
            }
        }




        impl From<VulnerabilityOutcome> for Option<ReportSectionFragment> {
            fn from(value: VulnerabilityOutcome) -> Self {
                match value {
                    $(
                        VulnerabilityOutcome::$name(outcome) => {
                            if outcome.is_empty() {
                                return None;
                            }
                            let length = outcome.iter().map(|(_, v)| v.len()).sum::<usize>();


                            let mut report_fragment = ReportSectionFragment::new(
                                $report_title.to_string(),
                                None,
                                $description.to_string(),
                                length,
                            );
                            let mut outcome_reports = vec![];
                            for (path, loc_snippets) in outcome.iter() {
                                let file_name = path.file_name().expect("couldnt get file name")  //TODO: make this a little more descriptive or propagate
                                .to_str()
                                .expect("no filename"); //TODO: make this a little more descriptive or propagate

                                for (loc, snippet) in loc_snippets.iter() {
                                    if let Loc::File(_, start, end) = loc{
                                        let file_contents = std::fs::read_to_string(path).expect("couldnt read file"); //TODO: propagate this or maybe just make more descriptive
                                        let start_line = utils::get_line_number(*start, &file_contents);
                                        let end_line = utils::get_line_number(*end, &file_contents);
                                        outcome_reports.push(OutcomeReport::new(
                                            file_name.to_string(),
                                            (start_line, end_line),
                                            snippet.to_string(),
                                        ));

                                }else{
                                    panic!("handle this TODO:");

                                }
                            }


                            }
                            report_fragment.outcomes = outcome_reports;
                            Some(report_fragment)

                        }



                    )+

                }

            }
        }




        //TODO: into tablefragment, propagate an eror if identifier nonce is not populated?





    };

}

//TODO: add section name
vulnerability!((
    DivideBeforeMultiply,
    "title goes here",
    "description goes here", //TODO: in the future maybe make this generated by gpt4
    "severity goes here"
));
